### ISSUE TITLE
Incoming Call fail

### ISSUE THREAD

**Issue by mudassirzulfiqar** [jojupiter/wiaCall#1]
Hi, Im getting this below error when I call 
`            SipServiceCommand.acceptIncomingCall(getApplicationContext(), accountID, callID, false);
`

`Failed to accept incoming call
    java.lang.Exception: Title:       pjsua_call_answer2(id, param.p_opt, prm.statusCode, param.p_reason, param.p_msg_data)
    Code:        171140
    Description: INVITE session already terminated (PJSIP_ESESSIONTERMINATED)
    Location:    ../src/pjsua2/call.cpp:498`
Also I have verified that the incoming call's id and the id im passing in the above method is the same

**Comment by cjcj125125** [comment]
cloud you give me demo?

**Comment by mudassirzulfiqar** [comment]
The error occurs on low end devices, I have tried on high end devices and I ran perfect.
